### ISSUE TITLE
Default value of polling rate is not valid

### ISSUE THREAD

**Issue by Compizfox** [Ruunyox/slurmvision#1]
After installing and running the software, I get the following error:

```
Unable to load user config at /root/.config/slurmvision.yml. Proceeding with default options...
Traceback (most recent call last):
  File "/usr/local/bin/slurmvision", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/slurmvision/scripts/__main__.py", line 67, in main
    inspector = Inspector(
  File "/usr/local/lib/python3.9/dist-packages/slurmvision/slurm/tools.py", line 70, in __init__
    raise ValueError(
ValueError: The requested polling rate, 1 s, for SQUEUE/SINFO is too low. Please use 10 s or more (or at least double check with your cluster admins)
```

It seems that the default value of the polling rate is 1 s, which is invalid.

**Comment by Ruunyox** [comment]
Great catch. The default value in the absence of a user config has been bumped to 10s ([4b952d1](https://github.com/Ruunyox/slurmvision/commit/4b952d1419e3ace69878d310c96e68f1ea8a50dc)).
